name: build-and-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  build:
    name: build-and-test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore Src/Bonzai.Blazor.Bootstrap.sln
    - name: Build
      run: dotnet build Src/Bonzai.Blazor.Bootstrap.sln --no-restore
    - name: Test
      run: dotnet test Src/Bonzai.Blazor.Bootstrap.sln --no-build --verbosity normal
